### ISSUE TITLE
Add location picking feature

### ISSUE THREAD

**Issue by oriash93** [oriash93/AutoClicker#1]
**Is your feature request related to a problem? Please describe.**
The user should be able to pick a location by clicking somewhere on the screen.

**Describe the solution you'd like**
This option will get the value from that pick action and feed it to the application.

**Additional context**
Could be tricky to implement UI-wise.

**Comment by james-s-w-clark** [comment]
What'd the tricky part be UI wise? 
I think you could keep it simple and a UI section like this:
`[Select coordinates] X:On Cursor, Y:On Cursor`
or (as x/y coordinates may not mean much to someone):
`[Select specific location] / [Use current location]`

**Comment by oriash93** [comment]
I think the tricky part is to capture the location picking instead of processing it as an actual mouse operation, since it could be anywhere on the screen. (I hope it's clear)

**Comment by james-s-w-clark** [comment]
In my use case, I wouldn't mind if the locating setting click occurs as an actual click as well.

I just had a look and saw it's a bit trickier to capture mouse coordinates when a click is outside if the application too.

A hack that comes to mind is opening a form which is - a rectangle the size of the screen 
- in full screen mode
- semi transparent
Would give an overlay where we can easily capture mouse coordinates, whilst also indicating to the user that they are selecting the coordinates on next click. It'd also prevent the click going through as a normal click

**Comment by oriash93** [comment]
A semi-transparent solution is the first thing I had in mind. Entering this mode for a single click, listening only to Esc or some other key to leave that mode with no capture.

If you have any other solution, or a way to implement it, feel free to suggest (or even write the code yourself 😉)

**Comment by james-s-w-clark** [comment]
Another C# autoclicker, had a try and the "Get" location button makes a window follow your mouse: https://github.com/robiot/AlphaClicker

**Comment by oriash93** [comment]
Thanks for the research, I will consider a similar solution
