### ISSUE TITLE
F6 and F7 hotkeys don't work when AutoClicker is not focused

### ISSUE THREAD

**Issue by BujuArena** [oriash93/AutoClicker#10]
To reproduce:

1. Set "Click Interval" to 16 milliseconds
2. Set "Mouse Button" to "Left"
3. Set "Click Type" to "Single"
4. Set "Click Position" "X" to "1600" and "Y" to "780"
5. Press F6
6. Press F7

Current behavior:
Clicking starts but doesn't stop.  Only logging out, which kills the process, causes clicking to stop.

Expected behavior:
When F7 is pressed, clicking is expected to stop.

**Comment by oriash93** [comment]
@AlexFolland Thanks for letting me know! Fixed :)
