### ISSUE TITLE
Hotkey settings

### ISSUE THREAD

**Issue by oriash93** [oriash93/AutoClicker#17]
Add the ability to set custom hotkeys, instead of the default F6/F7.

Includes:
- Changing the buttons display name and bindings.
- Adding the "Hotkey Settings" option (button/menu item - TBD)
- Validating the hotkeys - what keys are eligible? what keys are reserved?

Also:
- Should it be one key to toggle start/stop? Or should we stay with a separate key for each action?

**Comment by tacheometry** [comment]
Please! I've been searching forever for an autoclicker that allows changing your hotkey to mouse button 4/5. Still searching.

**Comment by oriash93** [comment]
@tacheometry Do you mean allowing auto clicks of mouse button 4/5?

**Comment by tacheometry** [comment]
@oriash93 No, I mean allowing to set your keybind to buttons on the mouse too, if you have any extra. All other autoclicker programs I found only allowed keys from the keyboard.
![extraButtonMouse](https://user-images.githubusercontent.com/39647014/98451578-b358b400-214f-11eb-932b-91a13fc890fc.png)

**Comment by oriash93** [comment]
@tacheometry I'll check this out and let you know 👍🏽

**Comment by oriash93** [comment]
@tacheometry Good news! I figured out how to do it and will push the code today. AutoClicker v3.0.0 will be released soon :)
