### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by oriash93** [oriash93/AutoClicker#18]
It would be nice for the application to have an icon to show in the taskbar.
Maybe also in the system tray if we finish #15 first.

Includes:
- Choosing an icon.
- Adding the file to the resources.
- Making sure the icon has the correct size and resolution.

**Comment by QuarantineMark** [comment]
![autoclicker](https://user-images.githubusercontent.com/39923466/97771282-76117800-1af8-11eb-8c81-bef3a6f03952.png)
![autoclicker_running](https://user-images.githubusercontent.com/39923466/97771285-80337680-1af8-11eb-8ecc-e2dc54c7a0a0.png)

**Comment by oriash93** [comment]
@QuarantineMark Thanks for the suggestion!
