### ISSUE TITLE
Change application icon when AutoClicker operation is running

### ISSUE THREAD

**Issue by oriash93** [oriash93/AutoClicker#32]
Inspired with the suggestion of two icons here #18.

Currently, we only show the gray icon.
It will be nice to toggle showing the green icon when the operation is running.

We need to see if and how WPF allows changing the icon in runtime.

**Comment by QuarantineMark** [comment]
Perhaps in the system tray at the very least #15.

**Comment by oriash93** [comment]
> Perhaps in the system tray at the very least #15.

actually the taskbar is more intuitive (and simple to implement)
