### ISSUE TITLE
no help with error

### ISSUE THREAD

**Issue by tplesser** [oriash93/AutoClicker#40]
I am using autoclicker and getting an error.  However, there is no suggested remedy nor any indication of where the error is occurring.  My goal is to auto-click on New Jersey every 10 seconds

[config New Jersey.docx](https://github.com/oriash93/AutoClicker/files/6109756/config.New.Jersey.docx)

**Comment by oriash93** [comment]
Hey, where are you clicking? What happens when you do?
Can you add a screenshot please?

**Comment by oriash93** [comment]
@tplesser closed for no response
