### ISSUE TITLE
3.0.0 doesn't launch 

### ISSUE THREAD

**Issue by mfsoup** [oriash93/AutoClicker#51]
**Describe the bug**
Version 3.0.0 doesn't launch. However, version 2.2 launches and works fine. Windows 10 19042.

**To Reproduce**
Download 3.0.0 and run it, nothing appears in taskbar or task manager. No error messages. 
Running 2.2, program appears in taskbar and window opens immediately.

**Expected behavior**
Program opens

**Screenshots**

**Comment by oriash93** [comment]
thanks, will be fixed ASAP

**Comment by oriash93** [comment]
Apparently, it was missing some resources. all zipped now and accessible [here ](https://github.com/oriash93/AutoClicker/releases/tag/v3.0.0)
