### ISSUE TITLE
Clicker is best . but can we do a solution so it could work in background . like running on a vps . it doesnt work if we minimize the screen . or close the vps 

### ISSUE THREAD

**Issue by Noumaniq24** [oriash93/AutoClicker#57]
**Is your feature request related to a problem? Please describe.**
A clear description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear description of what you want to happen.

**Additional context**

**Comment by oriash93** [comment]
Hey, what do you mean by VPS? When I am running the AutoClicker it still works when minimized.
Can you provide more details please?

**Comment by oriash93** [comment]
no response so i'm closing it
