### ISSUE TITLE
System.TypeInitializationException at SettingsUtils.cs

### ISSUE THREAD

**Issue by sole-dev** [oriash93/AutoClicker#58]
An error at `SettingsUtils.HotKeyChangedEvent += SettingsUtils_HotKeyChangedEvent;`(164th line)

I downloaded the source code and built it with VS2019, and this error was thrown.

**Comment by oriash93** [comment]
what source code version do you have? from master branch or v3.1.0?
I am building with VS2019 (Version 16.8.6) and not getting that error.

**Comment by sole-dev** [comment]
I have master branch source code, and I am building it with VS2019(16.11.0).

**Comment by oriash93** [comment]
Can you please try again?
Last time I had a successful build with VS2019 (Version 16.11.1) on branch master (commit `aab120df`).

**Comment by sole-dev** [comment]
Translation: System.Windows.Markup.XamlParseException: ''An exception was throwed about 'AutoClicker.Views.MainWindow' form that corresponds to designed binding condition."
![image](https://user-images.githubusercontent.com/86049679/130029574-8af2ca50-d6f5-4ed1-b7e1-71a890f66982.png)

**Comment by oriash93** [comment]
I was able to reproduce it. will work on a fix now :)

**Comment by oriash93** [comment]
@NewProgrammer1234 please try rebuilding now from branch master (commit `c6fb63c`)

**Comment by sole-dev** [comment]
It works perfectly now :) Thanks
