### ISSUE TITLE
Icon gets stuck on other autoclickers

### ISSUE THREAD

**Issue by playerinthematrix** [oriash93/AutoClicker#65]
The bug is, ever since I downloaded this and used other auto clickers the icon gets stuck, so I was wondering if there are other main files in my computer that I can remove? _hence file location_ please and would be most grateful!

**Comment by oriash93** [comment]
what do you mean by "icon gets stuck"? it stays in your taskbar?

**Comment by playerinthematrix** [comment]
> what do you mean by "icon gets stuck"? it stays in your taskbar?

like other programs of auto clickers, just wondering if there was a way to find the icon file itself and delete it. If not thats fine, and thank you for responding.

**Comment by oriash93** [comment]
If I understand correctly, you are looking the remove the application from your computer.
Just delete the files and that's it. No uninstall process is required :)
