### ISSUE TITLE
AutoClicker does not switch button display after becoming inactive

### ISSUE THREAD

**Issue by ExternalService** [oriash93/AutoClicker#74]
Clicking the "start" button, then clicking on another window to make AutoClicker no longer the active window but still visible on the screen. Using the "stop" hotkey to stop the clicking, it is observed that the display of the "start" and "stop" buttons in AutoClicker does not switch.

Open AutoClicker
Click on the "start" button
Click on another window to make AutoClicker inactive but still visible on the screen
Use the "stop" hotkey to stop clicking
Observe that the display of the "start" and "stop" buttons does not switch

Expected behavior
When the "stop" hotkey is used to stop the clicking, the display of the "start" button should switch back to its original state, indicating that clicking has stopped.

**Comment by oriash93** [comment]
Hey @ExternalService thanks for taking the time to open a bug!
I managed to reproduce it and will try to work on a fix.
