### ISSUE TITLE
Inconsistent security scans

### ISSUE THREAD

**Issue by 6ixtyGems** [oriash93/AutoClicker#79]
I've scanned the zip file with https://www.virustotal.com and it came up with "trojan.malware"
![image_2024-04-06_124528920](https://github.com/oriash93/AutoClicker/assets/166221654/2c14fd73-3f5d-4809-a951-92f0f24e4a06)

**Comment by Neimod2004** [comment]
I scanned just the exe and it found 2 issues, 1 of them was a malware warning

[https://www.virustotal.com/gui/file/a8ce190c42d78e56920810c2d2534cdb90f22817d63cad7cef475c77e7b3f126](https://www.virustotal.com/gui/file/a8ce190c42d78e56920810c2d2534cdb90f22817d63cad7cef475c77e7b3f126)

**Comment by digitalyoshixi** [comment]
compiling from scratch does not trigger any detections. https://www.virustotal.com/gui/file/278bffe3a14e01817fce6bebfdec81258e8495b0be9a242ed55c58e70ea6e2a2?nocache=1
the filesize appears to be larger on the release page

**Comment by omar-chaar** [comment]
> compiling from scratch does not trigger any detections. https://www.virustotal.com/gui/file/278bffe3a14e01817fce6bebfdec81258e8495b0be9a242ed55c58e70ea6e2a2?nocache=1 the filesize appears to be larger on the release page

Looks like that the exe file from the release page is an outdated one, that would explain the difference. 
Later I will check the build of the release date and compare the hashes with md5sum or sha1sum. If they are the same the release likely wasn't modified in any way, you can do it if you want. I will report my findings later here and in virus total.

**Comment by oriash93** [comment]
Hey all, thanks for taking the time to investigate this!
I am still unsure why VirusTotal is flagging this as malware.
In the meantime, I have published a new release ([v3.3.0](https://github.com/oriash93/AutoClicker/releases/tag/v3.3.0)), which includes the .zip file with the .exe and the necessary resources, which seems to pass the scanning:

![image](https://github.com/user-attachments/assets/c0c96b24-b6f4-4ef6-ba93-26d6dd464537)
![image](https://github.com/user-attachments/assets/8c9ab334-3bc6-4b63-a523-5f565774cff2)


Please let me know if you discover anything noteworthy.
